name: Bug Report
description: Create a bug report to help improve
title: 'Bug: '
body:

  # Tip to warn of checking for existing issues
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Have you checked for similar issues? There's a possibility the bug you are experiencing has already been reported. Please do a thorough search before creating a new issue.

  # Description
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  # Step to reproduce
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  # Version
  - type: input
    id: app_version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: "e.g. 0.14.0-alpha3"
    validations:
      required: true

  # OS type
  - type: dropdown
    id: os
    attributes:
      label: Affected platforms
      description: |
        Select all or any platform that you see this issue on. This helps us determine if it's something platform-specific or in the core.
      multiple: true
      options:
        - 📱 Android
        - 📲 iOS
        - 💻 macOS
        - 🪨 Rosetta (macOS Catalyst)
        - 🪟 Windows
        - 🪟 WPF
        - 🐧 GTK
        - 🐧 Linux Framebuffer
        - ⌨️ Skia Desktop
        - 🕸️ WebAssembly
        - ❓ Other
        - ☹️ I was unable to test on other platforms

  # OS Version
  - type: input
    id: os_version
    attributes:
      label: Platform version
      description: Which version of your OS are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy or <kbd>🍏</kbd> (in menu bar) and <kbd>About This Mac</kbd>
      placeholder: "e.g. 10.0.22621.1848"
    validations:
      required: true

  # Note that the user should always upload the report rather than pasting it
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please **upload** the log file by clicking "Attach files".
        >
        > Feel free to remove sensitive information such as your usernames or drive names.

  # Log File
  - type: textarea
    attributes:
      label: Log File
      description: |
        Please upload the log file as an attachment
      placeholder: |
        Copy the log from the crash window or upload as an upload it from the log location.
    validations:
      required: true

  # Separator
  - type: markdown
    attributes:
      value: |
        ---

  # Additional Comments
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the issue.
